name: Deploy

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  Deploy:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (
        github.event.pull_request.merged == true &&
        contains(github.event.pull_request.labels.*.name, 'release') &&
        (
          github.event.pull_request.base.ref == 'main' ||
          github.event.pull_request.base.ref == 'master'
        )
      )

    runs-on: ubuntu-24.04

    strategy:
      matrix:
        dotnet-version: [10.0.x]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install Cake
        run: dotnet tool install --global Cake.Tool

      - name: Build
        run: |
          cp LICENSE NETCore.Keycloak.Client/
          dotnet cake build.cake --target=Build

      - name: NuGet login
        id: login
        uses: NuGet/login@v1
        with:
          user: ${{ vars.NUGET_USERNAME }}

      - name: Publish package
        run: |
          dotnet nuget push \
            NETCore.Keycloak.Client/bin/Release/*.nupkg \
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" \
            --source https://api.nuget.org/v3/index.json